/** 
 * KittopiaTech - A Kopernicus Visual Editor
 * Copyright (c) Thomas P., BorisBee, KCreator, Gravitasi
 * Licensed under the Terms of a custom License, see LICENSE file
 */

using System;
using UnityEngine;

namespace Kopernicus
{
    namespace UI
    {
        /// <summary>
        /// Defines the position of a window
        /// </summary>
        [AttributeUsage(AttributeTargets.Class, Inherited = false)]
        public class Position : Attribute
        {
            /// <summary>
            /// The rect generated by the Attribute
            /// </summary>
            public Rect Value { get; set; }

            /// <summary>
            /// Creates a rect instance from the given parameters
            /// </summary>
            public Position(Rect source)
            {
                Value = new Rect(source);
            }

            /// <summary>
            /// Creates a rect instance from the given parameters
            /// </summary>
            public Position(Vector2 position, Vector2 size) : this(new Rect(position, size)) { }

            /// <summary>
            /// Creates a rect instance from the given parameters
            /// </summary>
            public Position(Single x, Single y, Single width, Single height) : this(new Rect(x, y, width, height)) { }
        }
    }
}